services:
  - type: web
    name: royals-industrial-league
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&       python manage.py collectstatic --noinput &&       gunicorn royals_industrial_league.wsgi:application --preload --workers=2 --timeout=120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: royals-industrial-league-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.9"
databases:
  - name: royals-industrial-league-db
    plan: free
