# Generated by Django 5.0.7 on 2025-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
    ]
