# Generated by Django 5.0.7 on 2025-09-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_fixture_is_bye'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='roster_limit',
            field=models.PositiveIntegerField(default=22, help_text="Maximum players allowed on this season's roster"),
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntrp', models.CharField(choices=[('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0')], max_length=3)),
                ('is_captain', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rosters', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='league.season')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name'],
                'unique_together': {('season', 'player')},
            },
        ),
    ]
