# Generated by Django 5.0.7 on 2025-09-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_season_roster_limit_rosterentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark this as the current active season'),
        ),
    ]
