# Generated by Django 5.0.7 on 2025-09-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_season_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_points', to='league.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_points', to='league.player')),
            ],
            options={
                'ordering': ['fixture__date', 'player__last_name', 'player__first_name'],
                'unique_together': {('fixture', 'player')},
            },
        ),
        migrations.CreateModel(
            name='SlotScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_code', models.CharField(choices=[('S1', 'Singles 1'), ('S2', 'Singles 2'), ('S3', 'Singles 3'), ('D1', 'Doubles 1'), ('D2', 'Doubles 2'), ('D3', 'Doubles 3')], max_length=2)),
                ('home_games', models.PositiveIntegerField(default=0)),
                ('away_games', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('T', 'Tie'), ('WF', 'Win by forfeit'), ('LF', 'Loss by forfeit')], max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_scores', to='league.fixture')),
            ],
            options={
                'ordering': ['fixture__date', 'slot_code'],
                'unique_together': {('fixture', 'slot_code')},
            },
        ),
    ]
