# Generated by Django 5.0.7 on 2025-09-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_playermatchpoints_slotscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_substitute',
            field=models.BooleanField(default=False, help_text='Mark this record as the global external substitute.'),
        ),
    ]
