# Generated by Django 5.0.7 on 2025-09-08 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_is_substitute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(choices=[('0830', '08:30'), ('1000', '10:00'), ('1130', '11:30')], max_length=4)),
                ('slot_code', models.CharField(choices=[('S1', 'Singles 1'), ('S2', 'Singles 2'), ('S3', 'Singles 3'), ('D1', 'Doubles 1'), ('D2', 'Doubles 2'), ('D3', 'Doubles 3')], max_length=2)),
                ('target_type', models.CharField(choices=[('AGAINST_US', 'Against Us (opponent in this fixture)'), ('OTHER_TEAM', 'Other Team')], default='OTHER_TEAM', max_length=12)),
                ('target_team_name', models.CharField(blank=True, help_text='Name of the team they will sub for', max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plans', to='league.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plans', to='league.player')),
            ],
            options={
                'ordering': ['fixture__date', 'timeslot', 'player__last_name', 'player__first_name'],
                'unique_together': {('fixture', 'player', 'timeslot')},
            },
        ),
        migrations.CreateModel(
            name='SubResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timeslot', models.CharField(choices=[('0830', '08:30'), ('1000', '10:00'), ('1130', '11:30')], max_length=4)),
                ('kind', models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], max_length=1)),
                ('slot_code', models.CharField(choices=[('S1', 'Singles 1'), ('S2', 'Singles 2'), ('S3', 'Singles 3'), ('D1', 'Doubles 1'), ('D2', 'Doubles 2'), ('D3', 'Doubles 3')], max_length=2)),
                ('target_type', models.CharField(choices=[('AGAINST_US', 'Against Us (opponent in this fixture)'), ('OTHER_TEAM', 'Other Team')], max_length=12)),
                ('target_team_name', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('T', 'Tie'), ('WF', 'Win by forfeit'), ('LF', 'Loss by forfeit')], max_length=2)),
                ('home_games', models.PositiveIntegerField(default=0)),
                ('away_games', models.PositiveIntegerField(default=0)),
                ('points_cached', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_results', to='league.fixture')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='league.subplan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_results', to='league.player')),
            ],
            options={
                'ordering': ['fixture__date', 'timeslot', 'player__last_name', 'player__first_name'],
            },
        ),
    ]
