# Generated by Django 5.0.7 on 2025-09-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_subplan_subresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(choices=[('0830', '08:30'), ('1000', '10:00'), ('1130', '11:30')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_availability', to='league.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_availability', to='league.player')),
            ],
            options={
                'ordering': ['fixture__date', 'player__last_name', 'player__first_name', 'timeslot'],
                'unique_together': {('player', 'fixture', 'timeslot')},
            },
        ),
    ]
