# Generated by Django 5.0.7 on 2025-09-09 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_notification_deliveryattempt_notificationreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('lineup_overdue_staff_email', models.BooleanField(default=False)),
                ('scores_overdue_staff_email', models.BooleanField(default=False)),
                ('lineup_published_email', models.BooleanField(default=False)),
                ('lineup_published_sms', models.BooleanField(default=False)),
                ('subplan_created_email', models.BooleanField(default=False)),
                ('subplan_created_sms', models.BooleanField(default=False)),
                ('result_posted_email', models.BooleanField(default=False)),
                ('result_posted_sms', models.BooleanField(default=False)),
                ('match_reminder_24h_email', models.BooleanField(default=False)),
                ('match_reminder_24h_sms', models.BooleanField(default=False)),
                ('availability_reminder_5d_email', models.BooleanField(default=False)),
                ('availability_reminder_5d_sms', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
