# Generated by Django 5.0.7 on 2025-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='invite_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
