# Generated by Django 5.0.7 on 2025-09-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_player_invite_sent_at_player_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_e164',
            field=models.CharField(blank=True, default='', help_text='Normalized E.164 phone (e.g., +13125551212)', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_opt_in',
            field=models.BooleanField(default=False, help_text='User explicitly consented to receive SMS.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SUPPRESSED', 'SUPPRESSED')], default='PENDING', max_length=32),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='league_deli_channel_5038a6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['notification', 'created_at'], name='league_deli_notific_9aeccf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event', 'created_at'], name='league_noti_event_4d9022_idx'),
        ),
    ]
