# Generated by Django 5.0.7 on 2025-09-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_phoneverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
    ]
