# Generated by Django 5.0.7 on 2025-09-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_remove_player_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='share_email_with_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='share_mobile_with_team',
            field=models.BooleanField(default=False),
        ),
    ]
