from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("schedule/", views.schedule_list, name="schedule_list"),
    path("fixture/<int:pk>/", views.fixture_detail, name="fixture_detail"),
    path("fixture/<int:fixture_id>/availability/", views.availability_update, name="availability_update"),
    # Captain tools live under /captain/... (not /admin/ to avoid clashing with Django Admin)
    path("captain/fixture/<int:fixture_id>/availability/", views.admin_availability_matrix, name="admin_availability_matrix"),
    path("captain/fixture/<int:fixture_id>/lineup/", views.admin_lineup_builder, name="admin_lineup_builder"),
    path("captain/", views.captain_dashboard, name="captain_dashboard"),
    path("profile/", views.profile_edit, name="profile_edit"),
    path("admin-panel/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-panel/schedule/", views.admin_manage_schedule, name="admin_manage_schedule"),
    path("admin-panel/roster/", views.admin_manage_roster, name="admin_manage_roster"),
    path("admin-panel/scores/", views.admin_manage_scores, name="admin_manage_scores"),
    path("api/availability/set/", views.availability_set_ajax, name="availability_set_ajax"),
    path("admin-panel/scores/", views.admin_manage_scores, name="admin_manage_scores"),
    path("admin-panel/scores/<int:fixture_id>/", views.admin_enter_scores, name="admin_enter_scores"),
    path("my-results/", views.my_results, name="my_results"),
    path("captain/subplan/<int:fixture_id>/new/", views.subplan_create, name="subplan_create"),
    path("captain/subplan/<int:plan_id>/edit/", views.subplan_edit, name="subplan_edit"),
    path("captain/subplan/<int:plan_id>/toggle/", views.subplan_toggle, name="subplan_toggle"),
    path("captain/subplan/<int:plan_id>/delete/", views.subplan_delete, name="subplan_delete"),
    path("captain/subresult/<int:fixture_id>/new/", views.subresult_create, name="subresult_create"),
    path("captain/subresult/from-plan/<int:plan_id>/", views.subresult_from_plan, name="subresult_from_plan"),
    path("captain/subresult/<int:sr_id>/edit/", views.subresult_edit, name="subresult_edit"),
    path("captain/subresult/<int:sr_id>/delete/", views.subresult_delete, name="subresult_delete"),
    path("ajax/sub-availability/", views.sub_availability_set_ajax, name="sub_availability_set_ajax"),
    path("notifications/mark-all-read/", views.notifications_mark_all_read, name="notifications_mark_all_read"),
    path("notifications/go/<int:receipt_id>/", views.notification_go, name="notification_go"),
    path("notifications/", views.notifications_list, name="notifications_list"),
    path("admin-panel/players/", views.admin_manage_players, name="admin_manage_players"),
    path("admin-panel/players/invite/", views.admin_player_invite, name="admin_player_invite"),
    path("admin-panel/players/<int:user_id>/toggle-active/", views.admin_player_toggle_active, name="admin_player_toggle_active"),
    path("admin-panel/players/<int:user_id>/toggle-captain/", views.admin_player_toggle_captain, name="admin_player_toggle_captain"),
    path("admin-panel/players/<int:user_id>/password-reset/", views.admin_player_reset_password, name="admin_player_reset_password"),
    path("admin-panel/players/<uuid:token>/accept-invite/", views.accept_invite, name="accept_invite"),
    path("admin-panel/players/<int:player_id>/resend-invite/", views.admin_player_resend_invite, name="admin_player_resend_invite"),
    # SMS opt-in API
    path("api/sms/start/", views.sms_start, name="sms_start"),
    path("api/sms/verify/", views.sms_verify, name="sms_verify"),
    path("api/sms/consent/", views.sms_consent, name="sms_consent"),
    path("my-team/", views.my_team_view, name="my_team"),
    path("admin-panel/playoff-eligibility/", views.admin_playoff_eligibility, name="admin_playoff_eligibility"),
    path("admin-panel/standings/", views.admin_league_standings, name="admin_league_standings"),
    path("admin-panel/schedule/export-csv/", views.admin_schedule_export_csv, name="admin_schedule_export_csv"),
]
